name: PVPGame
version: '${project.version}'
main: newamazingpvp.plugin.PVPGame
api-version: '1.21'
folia-supported: true

commands:
  setview:
    description: toggle view
    usage: /setvuew <sim> <render>
  givecustomitem:
    description: gives a custom item
    usage: /givecustomitem [item]
    aliases: /gci